module.exports = {
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  PAYOUT_SUCCESSFUL: "PAYOUT_SUCCESSFUL",
  STRIPE_ACCOUNT_CREATED: "STRIPE_ACCOUNT_CREATED",
  ROYALTY_DISTRIBUTION: "ROYALTY_DISTRIBUTION",
  PUSHUSER_APPROVED: "PUSHUSER_APPROVED",
  PRODUCT_BOUGHT: "PRODUCT_BOUGHT",
  NEW_PLAY: "NEW_PLAY",
  USER_VERIFIED: "USER_VERIFIED"
}