hy6module.exports = {
    CREATING_GAMES: "CREATING_GAMES",
    PENDING: "PENDING",
    PLAYING_VOTING: "PLAYING_VOTING",
    BUILDING: "BUILDING",
    MARKETING: "MARKETING",
    DISTRIBUTION: "DISTRIBUTION"
}
