module.exports = {
    BY: "by",
    FOR: "for",
    PAY: "pay",
    PUSHUSER: "pushuser",
    ENTER: "enter",
    ACCEPTED: "accepted",
    AGREED: "agreed",
    INTO: "into",
    ROYALTY: "royalty",
    BRAND: "brand",
    VOTE: "vote",
    ON: "on",
    USERS: "users",
    IDEA: "idea",
    EXCHANGE: "exchange",
    TO: "to",
    COMPLETE: "complete",
    ONBOARDING: "onboarding",
    ADD: "add",
    PRODUCT: "product",
    RULES: "rules",
    PURCHASE: "purchase"
}