const colors = [
  {
    name: 'Green',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_green.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Yellow',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_yellow.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Red',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_red.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Orange',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_orange.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Brown',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_brown.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Blue',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_blue.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Black',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_black.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Purple',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_purple.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'White',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_white.png',
    price: 100,
    description: 'HUB',
  },
  {
    name: 'Crimson',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_crimson.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Royal Blue',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_royal_blue.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Fluorescent Purp',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_fluorescent_purp.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Earth',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_earth.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Sun Orange',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_sun_orange.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Neon Green',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_neon_green.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Anti-flash white',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_anti_flash_white.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Silver',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_silver.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Money Green',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_money_green.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Canary Yellow',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_canary_yellow.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Crystal',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_crystal.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Yellow+Red ',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_yellow_red.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Sky Black',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_sky_black.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Gold',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_gold.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Blurp',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_blurp.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Shoebox Orange',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_shoebox_orange.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Machine Silver',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_machine_silver.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Ball Blue',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_ball_blue.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Power Violet',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_power_violet.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Yellow Kid',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_yellow_kid.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Onyx Mask',
    symbol: 'https://push-colors.s3.amazonaws.com/push_colors_onyx_mask.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  }
]

const hubs = [
  {
    name: 'Los Angeles',
    symbol: 'https://push-hubs.s3.amazonaws.com/LosAngeles_hub.png',
    price: 100,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'San Francisco',
    symbol: 'https://push-hubs.s3.amazonaws.com/SanFrancisco_hub.png',
    price: 100,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Chicago',
    symbol: 'https://push-hubs.s3.amazonaws.com/Chicago_hub.png',
    price: 100,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'New York',
    symbol: 'https://push-hubs.s3.amazonaws.com/NewYorkCity_hub.png',
    price: 100,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Houston',
    symbol: 'https://push-hubs.s3.amazonaws.com/Houston_hub.png',
    price: 100,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'Charlotte',
    symbol: 'https://push-hubs.s3.amazonaws.com/Charlotte_hub.png',
    price: 100,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'GO',
    symbol: 'https://push-hubs.s3.amazonaws.com/Go_hub.png',
    price: 0,
    description: 'HUB',
    hidden: true,
  },
  {
    name: 'CGI',
    symbol: 'https://push-hubs.s3.amazonaws.com/CGI_hub.png',
    price: 0,
    description: 'HUB',
  },
  {
    name: 'Cartoon',
    symbol: 'https://push-hubs.s3.amazonaws.com/Cartoon_hub.png',
    price: 0,
    description: 'HUB',
  },
  {
    name: 'Anime',
    symbol: 'https://push-hubs.s3.amazonaws.com/Anime_hub.png',
    price: 0,
    description: 'HUB',
  },
  {
    name: 'Puppet',
    symbol: 'https://push-hubs.s3.amazonaws.com/Puppet_hub.png',
    price: 0,
    description: 'HUB',
  },
  {
    name: 'Robot',
    symbol: 'https://push-hubs.s3.amazonaws.com/Robot_hub.png',
    price: 0,
    description: 'HUB',
  },
  {
    name: 'Superhero',
    symbol: 'https://push-hubs.s3.amazonaws.com/Superhero_hub.png',
    price: 0,
    description: 'HUB',
  }
]

const creativities = [
  {
    name: 'Numbers',
    symbol: 'https://push-types.s3.amazonaws.com/numbers_type.png',
    price: 100,
    description: 'Numbers user type',
  },
  {
    name: 'Sound',
    symbol: 'https://push-types.s3.amazonaws.com/sound_type.png',
    price: 100,
    description: 'Sound user type',
  },
  {
    name: 'Word',
    symbol: 'https://push-types.s3.amazonaws.com/words_type.png',
    price: 100,
    description: 'Word user type',
  },
  {
    name: 'Visual',
    symbol: 'https://push-types.s3.amazonaws.com/visual_type.png',
    price: 100,
    description: 'Visual user type',
  },
  {
    name: 'Voice',
    symbol: 'https://push-types.s3.amazonaws.com/voice_type.png',
    price: 100,
    description: 'Voice user type',
  },
  {
    name: 'Hands',
    symbol: 'https://push-types.s3.amazonaws.com/hands_type.png',
    price: 100,
    description: 'Hands user type',
  },
  {
    name: 'Ideas',
    symbol: 'https://push-types.s3.amazonaws.com/ideas_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Multi Tasker',
    symbol: 'https://push-types.s3.amazonaws.com/multi_tasker_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Artist',
    symbol: 'https://push-types.s3.amazonaws.com/artist_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Communication',
    symbol: 'https://push-types.s3.amazonaws.com/communication_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Lyrics',
    symbol: 'https://push-types.s3.amazonaws.com/lyrics_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Photographer',
    symbol: 'https://push-types.s3.amazonaws.com/photographer_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Data',
    symbol: 'https://push-types.s3.amazonaws.com/data_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Philosopher',
    symbol: 'https://push-types.s3.amazonaws.com/philosopher_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Aesthetics',
    symbol: 'https://push-types.s3.amazonaws.com/aesthetics_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Strategist',
    symbol: 'https://push-types.s3.amazonaws.com/strategist_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Historian',
    symbol: 'https://push-types.s3.amazonaws.com/historian_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'AI',
    symbol: 'https://push-types.s3.amazonaws.com/ai_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Wisdom',
    symbol: 'https://push-types.s3.amazonaws.com/wisdom_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Collector',
    symbol: 'https://push-types.s3.amazonaws.com/collector_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Skateboarding',
    symbol: 'https://push-types.s3.amazonaws.com/skateboarding_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Comics',
    symbol: 'https://push-types.s3.amazonaws.com/comics_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Frequencies',
    symbol: 'https://push-types.s3.amazonaws.com/frequencies_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Past and Future',
    symbol: 'https://push-types.s3.amazonaws.com/past_future_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Custom Transpo',
    symbol: 'https://push-types.s3.amazonaws.com/custom_transpo_type.png',
    price: 0,
    description: '',
    hidden: true,
  },
  {
    name: 'Taste',
    symbol: 'https://push-types.s3.amazonaws.com/taste_type.png',
    price: 0,
    description: '',
    hidden: true,
  }
]

module.exports = { colors, hubs, creativities }
